export const ALLOWED_CATEGORIES = [
  'Food',
  'Transport',
  'Shopping',
  'Bills',
  'Groceries',
  'Entertainment',
  'Health',
  'Education',
  'Fitness',
  'Pets',
  'Gifts',
  'Travel',
  'Other',
] as const;

export type CategoryName = (typeof ALLOWED_CATEGORIES)[number];

export function isCategoryName(value: string): value is CategoryName {
  return (ALLOWED_CATEGORIES as readonly string[]).includes(value);
}

export interface CategoryRule {
  category: CategoryName;
  words: string[];
}

export const CATEGORY_RULES: readonly CategoryRule[] = [
  {
    category: 'Food',
    words: [
      'pizza',
      'burger',
      'restaurant',
      'dinner',
      'lunch',
      'breakfast',
      'cafe',
      'coffee',
      'tea',
      'snack',
      'meal',
      'food',
      'swiggy',
      'zomato',
      'dominos',
      'kfc',
      'mcdonald',
      'sweets',
      'sweet',
      'icecream',
      'ice cream',
      'fuchka',
      'biryani',
      'biriyani',
      'paratha',
      'dosa',
      'idli',
      'momo',
      'momos',
      'noodles',
      'pasta',
      'sandwich',
      'fries',
      'cake',
      'pastry',
      'bakery',
      'juice',
      'soda',
      'chips',
      'chocolate',
      'curry',
      'tandoori',
      'grill',
      'barbecue',
      'bbq',
      'takeaway',
      'delivery',
      'chaat',
      'kebab',
      'fried rice',
      'chowmein',
      'dessert',
      'street food',
      'thali',
      'rolls',
      'subway',
      'footlong',
      'donut',
      'donuts',
      'pancake',
      'waffle',
      'salad',
      'starbucks',
      'pizza hut',
      'burger king',
    ],
  },
  {
    category: 'Transport',
    words: [
      'uber',
      'ola',
      'rapido',
      'taxi',
      'cab',
      'metro',
      'bus',
      'train',
      'flight',
      'fuel',
      'petrol',
      'diesel',
      'parking',
      'toll',
      'auto',
      'rickshaw',
      'metro card',
      'smart card',
      'commute',
      'ride',
      'car rental',
      'bike rental',
      'gas',
      'cng',
      'ev charging',
      'ferry',
      'tram',
      'airfare',
      'bus fare',
      'train ticket',
      'auto fare',
      'petrol pump',
      'e-rickshaw',
    ],
  },
  {
    category: 'Shopping',
    words: [
      'amazon',
      'flipkart',
      'myntra',
      'clothes',
      'shirt',
      'shoes',
      'shopping',
      'purchase',
      'bought',
      'mall',
      'electronics',
      'headphones',
      'phone',
      'watch',
      'laptop',
      'tablet',
      'accessories',
      'bag',
      'jeans',
      'dress',
      'jacket',
      'saree',
      'kurta',
      'footwear',
      'sneakers',
      'cosmetics',
      'makeup',
      'perfume',
      'gadget',
      'appliance',
      'furniture',
      'home decor',
      'sale',
      'online order',
      'cash on delivery',
      'sunglasses',
      'wallet',
      'belt',
      'jewellery',
      'jewelry',
    ],
  },
  {
    category: 'Bills',
    words: [
      'bill',
      'electricity',
      'water bill',
      'internet',
      'wifi',
      'broadband',
      'mobile recharge',
      'recharge',
      'rent',
      'gas bill',
      'insurance',
      'electricity bill',
      'phone bill',
      'dth',
      'cable tv',
      'maintenance',
      'emi',
      'loan',
      'credit card',
      'utility',
      'utilities',
      'prepaid',
      'postpaid',
      'house rent',
      'society maintenance',
    ],
  },
  {
    category: 'Groceries',
    words: [
      'grocery',
      'groceries',
      'vegetables',
      'vegetable',
      'fruits',
      'fruit',
      'milk',
      'bread',
      'rice',
      'atta',
      'dal',
      'supermarket',
      'dmart',
      'eggs',
      'meat',
      'chicken',
      'fish',
      'spices',
      'oil',
      'sugar',
      'salt',
      'flour',
      'pulses',
      'curd',
      'yogurt',
      'butter',
      'cheese',
      'snacks',
      'biscuits',
      'detergent',
      'soap',
      'shampoo',
      'toothpaste',
      'toiletries',
      'kitchen',
      'pantry',
      'wholesale',
      'kirana',
      'sabzi',
    ],
  },
  {
    category: 'Entertainment',
    words: [
      'movie',
      'cinema',
      'netflix',
      'spotify',
      'prime video',
      'concert',
      'game',
      'gaming',
      'subscription',
      'theatre',
      'theater',
      'popcorn',
      'disney',
      'hotstar',
      'zee5',
      'sony liv',
      'amazon prime',
      'hoichoi',
      'fancode',
      'watcho',
      'mx player',
      'ott play',
      'youtube premium',
      'music',
      'arcade',
      'bowling',
      'zoo',
      'museum',
      'amusement',
      'theme park',
      'event',
      'tickets',
      'show',
      'ott',
      'disney plus',
    ],
  },
  {
    category: 'Health',
    words: [
      'medicine',
      'medicines',
      'doctor',
      'hospital',
      'pharmacy',
      'medical',
      'clinic',
      'health',
      'dental',
      'dentist',
      'checkup',
      'surgery',
      'therapy',
      'lab test',
      'blood test',
      'xray',
      'prescription',
      'tablets',
      'vitamins',
      'supplements',
      'eyewear',
      'glasses',
      'physiotherapy',
      'vaccination',
      'ambulance',
      'consultation',
      'optician',
    ],
  },
  {
    category: 'Education',
    words: [
      'course',
      'udemy',
      'coursera',
      'books',
      'textbook',
      'ebook',
      'tuition',
      'class',
      'school',
      'college',
      'university',
      'exam',
      'certification',
      'online course',
      'workshop',
      'seminar',
      'training',
      'stationery',
      'notebook',
      'fee',
      'fees',
      'study',
      'coaching',
      'admission',
      'audiobook',
      'learning',
    ],
  },
  {
    category: 'Fitness',
    words: [
      'gym',
      'fitness',
      'workout',
      'yoga',
      'supplement',
      'protein',
      'trainer',
      'gym membership',
      'crossfit',
      'pilates',
      'sports',
      'equipment',
      'dumbbell',
      'treadmill',
      'personal trainer',
      'dietitian',
      'protein powder',
      'creatine',
      'zumba',
      'aerobics',
      'swim',
      'swimming',
    ],
  },
  {
    category: 'Pets',
    words: [
      'pet',
      'dog',
      'cat',
      'vet',
      'veterinary',
      'pet food',
      'grooming',
      'dog food',
      'cat food',
      'pet care',
      'aquarium',
      'pet toys',
      'pet grooming',
      'animal',
      'bird',
      'pet supplies',
      'dog collar',
    ],
  },
  {
    category: 'Gifts',
    words: [
      'gift',
      'birthday',
      'wedding',
      'anniversary',
      'present',
      'gifting',
      'gift card',
      'flowers',
      'bouquet',
      'chocolate box',
      'diwali gift',
      'secret santa',
      'greetings',
      'hamper',
    ],
  },
  {
    category: 'Travel',
    words: [
      'hotel',
      'airbnb',
      'hostel',
      'trip',
      'tour',
      'resort',
      'vacation',
      'holiday',
      'visa',
      'baggage',
      'luggage',
      'sightseeing',
      'travel',
      'booking',
      'cruise',
      'camp',
      'adventure',
      'staycation',
      'itinerary',
      'excursion',
    ],
  },
];

export interface CategorySeed {
  name: CategoryName;
  emoji: string;
}

export const CATEGORY_SEEDS: readonly CategorySeed[] = [
  { name: 'Food', emoji: '🍽️' },
  { name: 'Transport', emoji: '🚕' },
  { name: 'Shopping', emoji: '🛍️' },
  { name: 'Bills', emoji: '🧾' },
  { name: 'Groceries', emoji: '🛒' },
  { name: 'Entertainment', emoji: '🎬' },
  { name: 'Health', emoji: '💊' },
  { name: 'Education', emoji: '📚' },
  { name: 'Fitness', emoji: '💪' },
  { name: 'Pets', emoji: '🐾' },
  { name: 'Gifts', emoji: '🎁' },
  { name: 'Travel', emoji: '✈️' },
  { name: 'Other', emoji: '📦' },
];
